### ISSUE TITLE
Top Level API

### ISSUE THREAD

**Issue by sorodrigo** [Vizzuality/vizz-globe#2]
### Issue or proposal
I don't fully understand how the `vizz-globe` classes will get the instantiated cesium viewer with the proposed API. At a first glance it looks like it depends on side-effects (binding cesium to some global scope like `window`).

I think that a friendlier API would be to let the user get the reference of vizz-globe and include the layers, points, grid, path, etc in it.

### Additional Details

**Proposed API**
```js
import VizzGlobe, { Layers, Points, Grid, Path } from 'vizz-globe';

VizzGlobe.init(conf);
```

**Comment by tomasmoose** [comment]
Good point let's keep it simple, also, it might be a good idea to make the user create the instance so we avoid that confusion, or in theory, they want multiple instances. Then we can use this reference however we want. 

``` javascript
import VizzGlobe from 'vizz-globe';

const globeInstance = new VizzGlobe(...configurations)

globeInstance.layers.add
globeInstance.points.add
globeInstance.path.add
```
etc...
